# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsign.SignPanel')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsign.Playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='sign',
            name='code_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textpanel',
            name='num_lines',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textpanel',
            name='line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='textpanel',
            name='line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='textpanel',
            name='line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playlist',
            name='panels',
            field=models.ManyToManyField(through='roadsign.PlaylistItem', to='roadsign.SignPanel'),
        ),
    ]
