# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsign', '0002_auto_20170518_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpanel',
            name='num_lines',
            field=models.IntegerField(default=3),
        ),
    ]
